import { useState } from 'react'
import { Link } from 'react-router-dom'
import { jobAPI } from '../services/api'
import LoadingSpinner from '../components/LoadingSpinner'

const ApplyJob = () => {
  // Form state
  const [jobUrl, setJobUrl] = useState('')
  
  // Workflow step state
  const [currentStep, setCurrentStep] = useState(1) // 1: URL input, 2: Extracted, 3: Tailored, 4: Applied
  
  // Data state
  const [workflowData, setWorkflowData] = useState(null) // Stores complete workflow result
  const [jobData, setJobData] = useState(null)
  const [tailoredResume, setTailoredResume] = useState('')
  const [applicationResult, setApplicationResult] = useState(null)
  
  // Loading and error state
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(null)
  const [loadingMessage, setLoadingMessage] = useState('')

  const resetForm = () => {
    setJobUrl('')
    setCurrentStep(1)
    setWorkflowData(null)
    setJobData(null)
    setTailoredResume('')
    setApplicationResult(null)
    setError(null)
    setLoading(false)
    setLoadingMessage('')
  }

  // Step 1: Extract job description
  const handleExtractDescription = async () => {
    if (!jobUrl.trim()) {
      setError({
        title: 'Validation Error',
        message: 'Please enter a job URL'
      })
      return
    }

    setLoading(true)
    setError(null)
    setLoadingMessage('Extracting job description from URL...')
    
    try {
      // Call the backend which does the full workflow
      // We'll store the result and show it progressively
      const response = await jobAPI.applyJob(jobUrl)
      
      // Store complete workflow data
      setWorkflowData(response.data)
      
      // Extract and display job data
      const { application } = response.data
      setJobData({
        title: application.jobTitle || 'Job Position',
        company: application.company || 'Company',
        description: application.job_description || '',
        platform: application.platform || 'Unknown'
      })
      
      // Move to step 2
      setCurrentStep(2)
      
    } catch (err) {
      console.error('Extract description error:', err)
      
      const errorData = err.response?.data || {}
      setError({
        title: errorData.error || 'Extraction Failed',
        message: errorData.message || 'Failed to extract job description',
        details: errorData.details || 'Please check the URL and try again'
      })
    } finally {
      setLoading(false)
      setLoadingMessage('')
    }
  }

  // Step 2: Show tailored resume (already generated by backend)
  const handleShowTailoredResume = () => {
    if (!workflowData) return
    
    setLoading(true)
    setLoadingMessage('Loading tailored resume...')
    
    // Simulate loading for UX
    setTimeout(() => {
      const { application } = workflowData
      setTailoredResume(
        `Your resume has been tailored for this position and saved.\n\n` +
        `File: ${application.tailored_resume_path}\n\n` +
        `The AI has optimized your resume to highlight relevant skills and experience for this ${application.jobTitle} position at ${application.company}.`
      )
      
      setCurrentStep(3)
      setLoading(false)
      setLoadingMessage('')
    }, 800)
  }

  // Step 3: Show application result (already submitted by backend)
  const handleShowApplicationResult = () => {
    if (!workflowData) return
    
    setLoading(true)
    setLoadingMessage('Checking application status...')
    
    // Simulate loading for UX
    setTimeout(() => {
      const { application, applyResult, message } = workflowData
      
      setApplicationResult({
        success: applyResult?.success || false,
        message: message || 'Application completed',
        applicationId: application.id,
        jobTitle: application.jobTitle,
        company: application.company,
        status: application.status,
        appliedAt: application.applied_at
      })
      
      setCurrentStep(4)
      setLoading(false)
      setLoadingMessage('')
    }, 800)
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="container mx-auto px-4 max-w-4xl">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-gray-800 mb-2">
            Apply to Job
          </h1>
          <p className="text-gray-600">
            Paste a job URL and let AI tailor your resume and auto-apply
          </p>
        </div>

        {/* Progress Steps */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <div className="flex items-center justify-between">
            {/* Step 1: URL Input */}
            <div className="flex flex-col items-center flex-1">
              <div className={`w-10 h-10 rounded-full flex items-center justify-center font-semibold ${
                currentStep >= 1 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-600'
              }`}>
                1
              </div>
              <p className="text-xs mt-2 text-center text-gray-600">Enter URL</p>
            </div>
            
            <div className={`flex-1 h-1 ${currentStep >= 2 ? 'bg-blue-600' : 'bg-gray-200'}`}></div>
            
            {/* Step 2: Extract */}
            <div className="flex flex-col items-center flex-1">
              <div className={`w-10 h-10 rounded-full flex items-center justify-center font-semibold ${
                currentStep >= 2 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-600'
              }`}>
                2
              </div>
              <p className="text-xs mt-2 text-center text-gray-600">Extract Job</p>
            </div>
            
            <div className={`flex-1 h-1 ${currentStep >= 3 ? 'bg-blue-600' : 'bg-gray-200'}`}></div>
            
            {/* Step 3: Tailor */}
            <div className="flex flex-col items-center flex-1">
              <div className={`w-10 h-10 rounded-full flex items-center justify-center font-semibold ${
                currentStep >= 3 ? 'bg-blue-600 text-white' : 'bg-gray-200 text-gray-600'
              }`}>
                3
              </div>
              <p className="text-xs mt-2 text-center text-gray-600">Tailor Resume</p>
            </div>
            
            <div className={`flex-1 h-1 ${currentStep >= 4 ? 'bg-blue-600' : 'bg-gray-200'}`}></div>
            
            {/* Step 4: Apply */}
            <div className="flex flex-col items-center flex-1">
              <div className={`w-10 h-10 rounded-full flex items-center justify-center font-semibold ${
                currentStep >= 4 ? 'bg-green-600 text-white' : 'bg-gray-200 text-gray-600'
              }`}>
                {currentStep >= 4 ? '✓' : '4'}
              </div>
              <p className="text-xs mt-2 text-center text-gray-600">Apply</p>
            </div>
          </div>
        </div>

        {/* Main Content Area */}
        <div className="bg-white rounded-lg shadow-md p-6">
          {/* Error Display */}
          {error && (
            <div className="mb-6 bg-red-50 border border-red-200 rounded-lg p-4">
              <div className="flex items-start">
                <svg
                  className="w-5 h-5 text-red-600 mt-0.5 mr-3 flex-shrink-0"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
                <div className="flex-1">
                  <h3 className="text-red-800 font-semibold mb-1">{error.title || 'Error'}</h3>
                  <p className="text-red-700 text-sm">{error.message}</p>
                  {error.details && (
                    <p className="text-red-600 text-sm mt-2">{error.details}</p>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* Loading State */}
          {loading && (
            <LoadingSpinner message={loadingMessage} />
          )}

          {/* Step 1: Job URL Input */}
          {!loading && currentStep === 1 && (
            <div>
              <label htmlFor="jobUrl" className="block text-sm font-medium text-gray-700 mb-2">
                Job Posting URL
              </label>
              <input
                type="url"
                id="jobUrl"
                value={jobUrl}
                onChange={(e) => setJobUrl(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && jobUrl.trim()) {
                    handleExtractDescription()
                  }
                }}
                placeholder="https://www.indeed.com/viewjob?jk=..."
                className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent"
              />
              <p className="mt-2 text-sm text-gray-500">
                Supported platforms: Indeed, Wellfound
              </p>
            </div>
          )}

          {/* Step 2: Display Extracted Job Description */}
          {!loading && currentStep === 2 && jobData && (
            <div>
              <div className="mb-4">
                <h2 className="text-2xl font-bold text-gray-800 mb-2">
                  {jobData.title}
                </h2>
                <p className="text-lg text-gray-600 mb-1">{jobData.company}</p>
                <span className="inline-block px-3 py-1 bg-blue-100 text-blue-800 text-sm rounded-full">
                  {jobData.platform}
                </span>
              </div>
              
              <div className="mb-4">
                <h3 className="text-lg font-semibold text-gray-700 mb-2">Job Description</h3>
                <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 max-h-96 overflow-y-auto">
                  <pre className="whitespace-pre-wrap text-sm text-gray-700 font-sans">
                    {jobData.description}
                  </pre>
                </div>
              </div>

              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <div className="flex items-start">
                  <svg
                    className="w-5 h-5 text-green-600 mt-0.5 mr-3 flex-shrink-0"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <div>
                    <p className="text-green-800 font-medium">Job description extracted successfully!</p>
                    <p className="text-green-700 text-sm mt-1">
                      Click "Tailor Resume" to optimize your resume for this position.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Step 3: Display Tailored Resume */}
          {!loading && currentStep === 3 && tailoredResume && (
            <div>
              <div className="mb-4">
                <h2 className="text-2xl font-bold text-gray-800 mb-2">
                  Tailored Resume
                </h2>
                <p className="text-gray-600 mb-4">
                  Your resume has been optimized for {jobData?.title} at {jobData?.company}
                </p>
              </div>
              
              <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 mb-4">
                <pre className="whitespace-pre-wrap text-sm text-gray-700 font-sans">
                  {tailoredResume}
                </pre>
              </div>

              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <div className="flex items-start">
                  <svg
                    className="w-5 h-5 text-blue-600 mt-0.5 mr-3 flex-shrink-0"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                    />
                  </svg>
                  <div>
                    <p className="text-blue-800 font-medium">Resume tailored successfully!</p>
                    <p className="text-blue-700 text-sm mt-1">
                      Review your tailored resume above, then click "Apply Now" to submit your application.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Step 4: Display Application Result */}
          {!loading && currentStep === 4 && applicationResult && (
            <div>
              {applicationResult.success ? (
                <div className="text-center py-8">
                  <div className="inline-flex items-center justify-center w-16 h-16 bg-green-100 rounded-full mb-4">
                    <svg
                      className="w-8 h-8 text-green-600"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M5 13l4 4L19 7"
                      />
                    </svg>
                  </div>
                  
                  <h2 className="text-2xl font-bold text-gray-800 mb-2">
                    Application Submitted Successfully!
                  </h2>
                  
                  <p className="text-gray-600 mb-6">
                    Your application for {applicationResult.jobTitle} at {applicationResult.company} has been submitted.
                  </p>
                  
                  <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 mb-6 text-left max-w-md mx-auto">
                    <h3 className="font-semibold text-gray-700 mb-2">Application Details</h3>
                    <div className="space-y-2 text-sm">
                      <div className="flex justify-between">
                        <span className="text-gray-600">Status:</span>
                        <span className="font-medium text-green-600">Applied</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Application ID:</span>
                        <span className="font-medium text-gray-800">#{applicationResult.applicationId}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-600">Submitted:</span>
                        <span className="font-medium text-gray-800">
                          {new Date(applicationResult.appliedAt).toLocaleString()}
                        </span>
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex justify-center gap-4">
                    <Link
                      to="/history"
                      className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
                    >
                      View Application History
                    </Link>
                    <button
                      onClick={resetForm}
                      className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition"
                    >
                      Apply to Another Job
                    </button>
                  </div>
                </div>
              ) : (
                <div className="text-center py-8">
                  <div className="inline-flex items-center justify-center w-16 h-16 bg-yellow-100 rounded-full mb-4">
                    <svg
                      className="w-8 h-8 text-yellow-600"
                      fill="none"
                      stroke="currentColor"
                      viewBox="0 0 24 24"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth={2}
                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
                      />
                    </svg>
                  </div>
                  
                  <h2 className="text-2xl font-bold text-gray-800 mb-2">
                    Partial Success
                  </h2>
                  
                  <p className="text-gray-600 mb-6">
                    Your resume was tailored successfully, but automatic submission encountered an issue.
                  </p>
                  
                  <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6 text-left max-w-md mx-auto">
                    <p className="text-yellow-800 text-sm">
                      {applicationResult.message}
                    </p>
                  </div>
                  
                  <div className="flex justify-center gap-4">
                    <Link
                      to="/history"
                      className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition"
                    >
                      View Application History
                    </Link>
                    <button
                      onClick={resetForm}
                      className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition"
                    >
                      Try Another Job
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Action Buttons */}
        {!loading && currentStep < 4 && (
          <div className="mt-6 flex justify-between">
            {currentStep === 1 ? (
              <Link
                to="/dashboard"
                className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition"
              >
                Back to Dashboard
              </Link>
            ) : (
              <button
                onClick={resetForm}
                className="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition"
              >
                Start Over
              </button>
            )}
            
            {currentStep === 1 && (
              <button
                onClick={handleExtractDescription}
                disabled={!jobUrl.trim()}
                className={`px-6 py-2 rounded-lg font-medium transition ${
                  jobUrl.trim()
                    ? 'bg-blue-600 text-white hover:bg-blue-700'
                    : 'bg-gray-300 text-gray-500 cursor-not-allowed'
                }`}
              >
                Extract Job Description
              </button>
            )}
            
            {currentStep === 2 && (
              <button
                onClick={handleShowTailoredResume}
                className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition font-medium"
              >
                Tailor Resume
              </button>
            )}
            
            {currentStep === 3 && (
              <button
                onClick={handleShowApplicationResult}
                className="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition font-medium"
              >
                Apply Now
              </button>
            )}
          </div>
        )}
      </div>
    </div>
  )
}

export default ApplyJob
